server:
  port: 8080
spring:
  application:
    name: brand-category-product-api
  datasource:
    url: jdbc:h2:mem:mss
    driver-class-name: org.h2.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console